config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  devise_for :shops, skip: :all
  # devise 必要なルーティングのみ使用
  devise_scope :shop do
    get 'sign_up' => 'shops/registrations#new', as: :new_shop_registration
    post 'sign_up' => 'shops/registrations#create', as: :shop_registration
    post 'sing_up' => 'shops/passwords#new', as: :new_shop_password
    get 'sign_in' => 'shops/sessions#new', as: :new_shop_session
    post 'sign_in' => 'shops/sessions#create', as: :shop_session
    delete 'sign_out' => 'shops/sessions#destroy', as: :destroy_shop_session
  end

  # ユーザー
  namespace :user do
    # メニュー
    resources :menus, only:[:show] do
      resources :item_groups, only:[:show]
      resource :grin, only:[:create]
      resource :dizzy, only:[:create]
      resource :happy, only:[:create]
      # リクエスト
      resources :requests, only:[:create,:new] do
        get :thanks, on: :collection
      end
    end
  end

  # ショップ
  namespace :shop do
    # お問い合わせ
    resource :inquiry, only:[:new,:create] do
      post :confirm, on: :collection
    end
    resources :requests, only:[:index, :show, :destroy]
    resources :categories,except:[:show,:new]
    # マイページ
    resource :mypages,except:[:new,:create] do
      get :top, on: :collection
      get :cancel, on: :collection
      get :password, on: :collection
      get :howto, on: :collection
      patch :update_password, on: :collection
    end
    # エモーション
    resources :emotions, only:[:index] do
      get :reset, on: :collection
    end
    # メニュー(shallow true)
    resources :menus, except: :new, shallow: true do
      get :two_d_code, on: :member
      # アイテムグループ(shallow true)
      resources :item_groups,only:[:create,:destroy,:edit,:update], shallow: true do
        get :move_higher, on: :member
        get :move_lower, on: :member
        # メニューアイテム
        resources :menu_items, except: :new do
          get :move_higher, on: :member
          get :move_lower, on: :member
        end
      end
    end
  end

  # 管理者
  namespace :admin do
    resource :session, only:[:new, :create, :destroy]
    resources :shops, except:[:create,:new]
    resources :deleted_shops, only:[:index,:show]
    resource :tax, only:[:show,:edit,:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
    layout 'layouts/admin'
    before_action :current_admin
    before_action :require_admin_sign_in!
    
    def index
        @shops = Shop.all.page(params[:page]).per(15)
    end

    def destroy
        shop = Shop.find(params[:id])
        deleted_shop = DeletedShop.duplicate(shop)
        begin
            ActiveRecord::Base.transaction do
                deleted_shop.save!
                shop.destroy!
                redirect_to admin_shops_path,:alert=>"Shopを削除しました。"
            end
        rescue
            redirect_to action: :cancel,:danger=>"削除に失敗しました。"
        end
    end

    def show
        @shop = Shop.find(params[:id])
    end

    def edit
        @shop = Shop.find(params[:id])
    end

    def update
        @shop = Shop.find(params[:id])
        if @shop.update(shop_params)
            redirect_to admin_shops_path
        else
            flash.now[:alert] = "failed"
            render :edit
        end
    end

    private
    def shop_params
        params.require(:shop).permit(:shop_name,:state,:city,:street,:postal_code,:phone_number,:email)
    end
end

app/controllers/shop/categories_controller.rb
class Shop::CategoriesController < ApplicationController
    before_action :authenticate_shop!

    def index
        @category = Category.new
        @categories = current_shop.categories
    end

    def create
        @category = Category.new(category_params)
        @category.shop_id = current_shop.id
        if @category.save
            redirect_to shop_categories_path, :notice =>'カテゴリを登録しました。'
        else
            flash.now[:alert] = '登録に失敗しました。'
            @categories = current_shop.categories
            render :index
        end
    end

    def destroy
        category = Category.find(params[:id])
        correct_shop(category) and return
        if category.destroy
            redirect_to shop_categories_path, :notice=>'カテゴリを削除しました。'
        else
            redirect_to shop_categories_path, :alert=>'アイテムグループに設定されているカテゴリは削除できません。'
        end
    end

    def edit
        @category = Category.find(params[:id])
        correct_shop(@category) and return
    end

    def update
        @category = Category.find(params[:id])
        correct_shop(@category) and return
        if @category.update(category_params)
            redirect_to shop_categories_path, :notice =>'カテゴリ名を変更しました。'
        else
            flash.now[:alert] = '更新に失敗しました。'
            @categories = current_shop.categories
            render :edit
        end
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/shop/emotions_controller.rb
class Shop::EmotionsController < ApplicationController
    before_action :authenticate_shop!
    
    def index
        # インスタンスメソッド・grin・happy・dizzyのカウントをハッシュで返す
        @emotions = current_shop.emotions
    end

    def reset
        grins = current_shop.grins
        happies = current_shop.happies
        dizzies = current_shop.dizzies
        grins.destroy_all
        happies.destroy_all
        dizzies.destroy_all
        redirect_to shop_emotions_path,:notice=>"エモーションをリセットしました。"
    end
end

app/controllers/shop/inquiries_controller.rb
class Shop::InquiriesController < ApplicationController
    before_action :authenticate_shop!
    
    def new
        @inquiry = Inquiry.new
    end

    def create
        @inquiry = Inquiry.new(inquiry_params)
        # paramsがbackの時、処理を中断
        render :new and return if params[:back]
        if @inquiry.valid?
            @inquiry.insert_shop_info(current_shop)
            InquiryMailer.send_mail(@inquiry).deliver_now
            redirect_to new_shop_inquiry_path,:notice=>"正常に送信されました。"
        else
            flash.now[:alert] = "送信に失敗しました。"
            render :new
        end
    end

    def confirm
        @inquiry = Inquiry.new(inquiry_params)
        if @inquiry.valid?
            render
        else
            flash.now[:alert] = "送信に失敗しました。"
            render :new
        end
    end
    
    private
    def inquiry_params
        params.require(:inquiry).permit(:name,:message)
    end
end

app/controllers/shop/item_groups_controller.rb
class Shop::ItemGroupsController < ApplicationController
    before_action :authenticate_shop!

    def create
        item_group = ItemGroup.new(item_group_params)
        item_group.menu_id = params[:menu_id]
        # IDチェック
        correct_shop(item_group.menu) and return
        if item_group.save
            redirect_to shop_menu_path(item_group.menu),:notice =>'アイテムグループを作成しました。'
        else
            redirect_to shop_menu_path(params[:menu_id]),:alert=>'登録に失敗しました。'
        end
    end

    def destroy
        item_group = ItemGroup.find(params[:id])
        # IDチェック
        correct_shop(item_group.menu) and return
        item_group.destroy
        redirect_to shop_menu_path(item_group.menu),:notice=>'アイテムグループを削除しました。'
    end

    def edit
        @item_group = ItemGroup.find(params[:id])
        # IDチェック
        correct_shop(@item_group.menu) and return
    end

    def update
        @item_group = ItemGroup.find(params[:id])
        # IDチェック
        correct_shop(@item_group.menu) and return
        if @item_group.update(item_group_params)
            redirect_to shop_item_group_menu_items_path(@item_group)
        else
            render :edit
        end
    end

    # 並べ替え用
    def move_higher
        item_group = ItemGroup.find(params[:id])
        # IDチェック
        correct_shop(item_group.menu) and return
        # positionカラム更新(gem:acts_as_list)
        item_group.move_higher
        @menu = item_group.menu
        # htmlならリダイレクト
        respond_to do |format|
            format.js
            format.html {redirect_to shop_menu_path(@menu)}
        end
    end

    # 並べ替え用
    def move_lower
        # move_higherとの違いは"move_lower"部分のみ
        item_group = ItemGroup.find(params[:id])
        correct_shop(item_group.menu) and return
        item_group.move_lower
        @menu = item_group.menu
        respond_to do |format|
            format.js
            format.html {redirect_to shop_menu_path(@menu)}
        end
    end

    private
    def item_group_params
        params.require(:item_group).permit(:category_id,:group_image)
    end
end

app/controllers/shop/menu_items_controller.rb
class Shop::MenuItemsController < ApplicationController
    before_action :authenticate_shop!

    def index
        @menu_item = MenuItem.new
        @item_group = ItemGroup.find(params[:item_group_id])
        # IDチェック
        correct_shop(@item_group.menu) and return
        @menu_items = MenuItem.where(item_group_id: @item_group.id)
    end

    def create
        @item_group = ItemGroup.find(params[:item_group_id])
        # IDチェック
        correct_shop(@item_group.menu) and return
        @menu_item = MenuItem.new(menu_item_params)
        @menu_item.item_group_id = @item_group.id
        if @menu_item.save
            redirect_to shop_item_group_menu_items_path(@item_group),:notice=>'アイテムを追加しました。'
        else
            @menu_items = MenuItem.where(item_group_id: params[:item_group_id])
            flash.now[:alert] = '登録に失敗しました。'
            render :index
        end
    end

    def update
        @menu_item = MenuItem.find(params[:id])
        # IDチェック
        correct_shop(@menu_item.item_group.menu) and return
        # 階層リンクの文字列保持(失敗時のrender)
        @item_name = @menu_item.item_name
        if @menu_item.update(menu_item_params)
            redirect_to shop_item_group_menu_items_path(@menu_item.item_group),:notice => "アイテムを更新しました。"
        else
            flash.now[:alert] = "更新に失敗しました。"
            render :edit
        end
    end

    def show
        @menu_item = MenuItem.find(params[:id])
        correct_shop(@menu_item.item_group.menu) and return
    end
    
    def edit
        @menu_item = MenuItem.find(params[:id])
        correct_shop(@menu_item.item_group.menu) and return
        # 階層リンクの文字列保持
        @item_name = @menu_item.item_name
    end

    def destroy
        menu_item = MenuItem.find(params[:id])
        correct_shop(menu_item.item_group.menu) and return
        menu_item.destroy
        redirect_to shop_item_group_menu_items_path(menu_item.item_group),:notice=>'アイテムを削除しました。'
    end
    
    # 並べ替え用
    def move_higher
        menu_item = MenuItem.find(params[:id])
        # IDチェック
        correct_shop(menu_item.item_group.menu) and return
        # positionカラム更新(gem:acts_as_list)
        menu_item.move_higher
        # htmlならリダイレクト、jsなら処理用のデータを渡す
        respond_to do |format|
            format.js {@menu_items = MenuItem.where(item_group_id: menu_item.item_group_id)}
            format.html {redirect_to shop_item_group_menu_items_path(menu_item)}
        end
    end

    # 並べ替え用
    def move_lower
        menu_item = MenuItem.find(params[:id])
        correct_shop(menu_item.item_group.menu) and return
        menu_item.move_lower
        respond_to do |format|
            format.js { @menu_items = MenuItem.where(item_group_id: menu_item.item_group_id)}
            format.html {redirect_to shop_item_group_menu_items_path(menu_item)}
        end
    end

    private
    def menu_item_params
        params.require(:menu_item).permit(:price,:item_name,:item_text,:item_image)
    end
end

app/controllers/shop/menus_controller.rb
class Shop::MenusController < ApplicationController
    before_action :authenticate_shop!
    
    def index
        @menu = Menu.new
        @menus = current_shop.menus
    end

    def create
        @menu = Menu.new(menu_params)
        @menu.shop_id = current_shop.id
        if @menu.save
            redirect_to shop_menu_path(@menu),:notice => 'メニューを作成しました。'
        else
            flash.now[:alert] = '作成に失敗しました。'
            @menus = current_shop.menus
            render :index
        end
    end

    def update
        @menu = Menu.find(params[:id])
        correct_shop(@menu) and return
        # 更新失敗時に階層リンクの文字が変わるのを防止
        @menu_name = @menu.menu_name
        if @menu.update(menu_params)
            redirect_to shop_menu_path(@menu),:notice=>'変更を保存しました。'
        else
            flash[:alert] = '更新に失敗しました。'
            render :edit
        end
    end

    def edit
        @menu = Menu.find(params[:id])
        correct_shop(@menu) and return
        # 更新失敗時に階層リンクの文字が変わるのを防止
        @menu_name = @menu.menu_name
    end

    def destroy
        menu = Menu.find(params[:id])
        correct_shop(menu) and return
        menu.destroy
        redirect_to shop_menus_path, :notice=>'メニューを削除しました。'
    end

    def show
        @menu = Menu.find(params[:id])
        correct_shop(@menu) and return
    end

    # 2次元コードの表示
    def two_d_code
        @menu = Menu.find(params[:id])
        correct_shop(@menu) and return
        # MENUのURL 2次元コードヘルパーで使用
        @url = user_menu_url(@menu)
        respond_to do |format|
            format.html{render layout: 'layouts/qrcode'}
            format.pdf do
                render  pdf: '2Dcode',
                        layout: 'layouts/qrcode',
                        encoding: 'utf-8'
            end
        end
    end

    private
    def menu_params
        params.require(:menu).permit(:menu_name, :color)
    end
end

app/controllers/shop/mypages_controller.rb
class Shop::MypagesController < ApplicationController
    before_action :authenticate_shop!
    
    def top
        # リクエスト5件まで取得(モデルにてorder)
        @requests = current_shop.requests.limit(5)
        # Shopモデルのインスタンスメソッド・happy・dizzy・grinのカウントをハッシュで返す
        @emotions = current_shop.emotions
    end

    def cancel
    end

    def show
    end

    def edit
    end

    def destroy
        deleted_shop = DeletedShop.duplicate(current_shop)
        begin
            ActiveRecord::Base.transaction do
                deleted_shop.save!
                current_shop.destroy!
                redirect_to root_path,:notice=>"退会処理が完了しました。"
            end
        rescue
            redirect_to action: :cancel,:notice=>"処理に失敗しました。"
        end
    end

    def update
        if current_shop.update(shop_params)
            redirect_to shop_mypages_path,:notice=>'変更を保存しました。'
        else
            flash.now[:alert] = "更新に失敗しました。"
            render :edit
        end
    end

    def password
    end

    def update_password
        if current_shop.update_with_password(shop_params)
            sign_in(current_shop, bypass: true)
            redirect_to shop_mypages_path, :notice=>"パスワードを変更しました。"
        else
            flash.now[:alert] = "変更に失敗しました。"
            render :password
        end
    end

    private
    def shop_params
        params.require(:shop).permit(:state,:city,:street,:phone_number,:shop_name,:postal_code,:email,:password,:password_confirmation,:current_password)
    end
end

app/controllers/shop/requests_controller.rb
class Shop::RequestsController < ApplicationController
    before_action :authenticate_shop!
    
    def index
        @requests = current_shop.requests.page(params[:page]).per(5)
    end

    def destroy
        @request = Request.find(params[:id])
        # apprication_controllerのメソッド・shop_id!=current_shop_idならリダイレクト&trueを返す
        correct_shop(@request) and return
        @request.destroy
        respond_to do |format|
            format.js {flash.now[:notice] = "リクエストを削除しました。"}
            format.html {redirect_to shop_requests_path,:notice=>"リクエストを削除しました。"}
        end
    end
end

app/controllers/shop/shops_controller.rb
class Shop::ShopsController < ApplicationController
    before_action :authenticate_shop!
    
    def top
        @requests = current_shop.requests
        happies = current_shop.happies
        dizzies = current_shop.dizzies
        grins = current_shop.grins
        @data = {'happy' => happies.count, 'dizzy' => dizzies.count, 'grin' => grins.count}
    end
end

app/controllers/shops/passwords_controller.rb
# frozen_string_literal: true

class Shops::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shops/sessions_controller.rb
# frozen_string_literal: true

class Shops::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/menus_controller.rb
class User::MenusController < ApplicationController
    layout 'layouts/user'
    
    def show
        @menu = Menu.find(params[:id])
        @emotions = @menu.shop.emotions
    end
end

app/views/shop/menus/_grouplist.html.haml
- @menu.item_groups.each do |item_group|
    .columns.is-vcentered.is-mobile.has-over-line
        .column.is-3
            -# 並び替えリンク　最後の{}はfalseでボタンを非表示にするため
            .columns.is-vcentered.is-mobile
                .column
                    = link_to_if(!item_group.first?,'▲', move_higher_shop_item_group_path(item_group), :id => item_group, remote: true, class:'button is-small is-rounded is-block'){}
                    = link_to_if(!item_group.last?,'▼', move_lower_shop_item_group_path(item_group), :id => item_group, remote: true, class:'button is-small is-rounded is-block'){}
                .column
                    = item_group.position
        .column.is-2
            =attachment_image_tag item_group, :group_image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size: '300x300'
        .column.is-3
            =item_group.category.name
        .column.is-4.text-right
            = link_to shop_item_group_menu_items_path(item_group),class:'button is-info is-small is-rounded strong' do
                %i.fas.fa-search
                %span.is-hidden-mobile 詳細
            = link_to shop_item_group_path(item_group),method: :delete,class:'button is-danger is-small is-rounded strong',data:{confirm:"削除してもよろしいですか？"} do
                %i.fas.fa-trash
                %span.is-hidden-mobile 削除

app/views/shop/menus/edit.html.haml
- content_for(:title) {"#{@menu_name}情報編集"}
.container
    .columns
        .column.is-3.is-hidden-mobile
            = render 'shop/sidebar'
        .column.is-8.main-content
            -# 階層リンク
            .links-nav.text-ex-small
                = link_to "メニュー管理",shop_menus_path
                >
                = link_to shop_menu_path(@menu) do
                    = @menu_name
                >編集
            -# メニュー編集フォーム
            %h2.text-large.has-under-line-pink.text-center
                %i.fas.fa-edit
                メニュー情報編集
            %p.text-center.text-small メニュー名・カラーを変更できます。
            .box.has-middle-margin
                = form_with model: @menu, url:{:controller=>'shop/menus',:action=>'update'},local: true do |f|
                    = render 'layouts/error-message', model: f.object
                    .columns
                        .column.is-8-desktop.is-offset-2-desktop
                            .field
                                = f.label :menu_name,'メニュー名',class:'label'
                                .control
                                    = f.text_field :menu_name,class:'input is-link'
                            .field
                                %span.label テーマカラー
                                = render 'layouts/select-colors', f: f
                            .field
                                .control.text-center
                                    = f.submit '変更を保存',class:'button is-link'
            .text-center.text-small
                = link_to shop_menu_path(@menu) do
                    戻る

app/views/shop/menus/index.html.haml
- content_for(:title) {'メニュー管理'}
.container
    .columns
        .column.is-3.is-hidden-mobile
            = render 'shop/sidebar'
        .column.is-8.main-content
            .columns
                .column.is-10-desktop.is-offset-1-desktop.is-12-tablet.is-offset-0-tablet
                    -# メニュー一覧
                    .text-center
                        %h2.text-large.has-under-line-pink
                            メニュー管理
                        %p.text-small 2次元コードの表示・編集・閲覧が行えます。
                    -# メニューがあるとき             
                    - if @menus.any?
                        .box.has-middle-margin
                            .columns.is-mobile
                                .column.is-3.text-small
                                    カラー
                                .column.is-4.text-small
                                    メニュー名
                            - @menus.each do |menu|
                                .columns.is-mobile.is-vcentered.has-over-line
                                    .column.is-3
                                        .ball{style:"background-color:#{menu.color}"}
                                    .column.is-4
                                        = menu.menu_name
                                    .column.is-5.text-right
                                        = link_to two_d_code_shop_menu_path(menu,format: :pdf), target: :_blank, class:'button is-small is-rounded' do
                                            %i.fas.fa-qrcode
                                            Code
                                        = link_to shop_menu_path(menu), class:'button is-info is-small is-rounded strong' do
                                            %i.fas.fa-search
                                            %span.is-hidden-mobile 詳細
                                        = link_to shop_menu_path(menu),method: :delete,class:'button is-danger is-small is-rounded strong',data:{confirm:"削除してもよろしいですか？\n削除するとアイテムグループとアイテムも全て削除されます。"} do
                                            %i.fas.fa-trash
                                            %span.is-hidden-mobile 削除

                    -# メニュー新規作成
                    .box.has-middle-margin
                        .text-center
                            %h3.text-large.has-under-line.is-inline-block
                                メニュー新規作成
                            %p.text-small 新しいメニューを作成します。
                        .has-middle-margin
                            - if current_shop.categories.any?
                                = form_with model: @menu, url: { :controller=>'shop/menus', :action=>'create'},local: true do |f|
                                    = render 'layouts/error-message', model: f.object
                                    .field
                                        = f.label :menu_name,'メニュー名',class:'label'
                                        .control
                                            = f.text_field :menu_name, class:'input is-link',placeholder:'メニューの見出しになります（8文字以内）'
                                    .field
                                        %span.label メニューカラー
                                        %p.text-small メニューのテーマカラーを選択して下さい。
                                        = render 'layouts/select-colors', f: f
                                    .field
                                        .control.text-center
                                            = f.submit 'メニュー作成', class:'button is-link'
                            - else
                                .text-center
                                    %p.strong
                                    = link_to shop_categories_path, class:'button is-primary' do
                                        カテゴリの登録が必要です

app/views/shop/menus/qrcode.html.haml
%p{style:"font-size:1.4em;"}
    = current_shop.shop_name
    さんの
    = @menu.menu_name
%div{style:"border-bottom:1px solid #{@menu.color}"}
%p
.codes
    -# 小サイズ 2*6=12個表示
    - 6.times do
        .color{style:"background-color:#{@menu.color};display:inline-block;"}
            .qrcode{style:"opacity:.8;"}
                = image_tag qrcode @url,290
        = image_tag qrcode @url,290
.codes
    -# 中サイズ 6個表示
    - 6.times do
        = image_tag qrcode @url,420

app/views/shop/menus/qrcode.pdf.haml
%p{style:"font-size:1.4em;"}
    = current_shop.shop_name
    さんの
    = @menu.menu_name
    の2次元コード
%div{style:"border-bottom:1px solid #{@menu.color}"}
%p
.codes
    -# 2*6=12個表示
    - 6.times do
        .color{style:"background-color:#{@menu.color};display:inline-block;"}
            .qrcode{style:"opacity:.8;"}
                = image_tag qrcode @url,290
        = image_tag qrcode @url,290
.codes
    - 6.times do
        = image_tag qrcode @url,420

app/views/shop/menus/show.html.haml
- content_for(:title) {"#{@menu.menu_name}"}
.container
    .columns
        .column.is-3.is-hidden-mobile
            = render 'shop/sidebar'
        .column.is-8.main-content

            -# 階層リンク
            .links-nav.text-ex-small
                = link_to "メニュー管理",shop_menus_path
                >
                = @menu.menu_name

            -# メニュー一覧
            .columns
                .column.is-10-desktop.is-offset-1-desktop.is-12-tablet.is-offset-0-tablet
                    %h2.text-large.has-under-line-pink.text-center
                        メニュー情報
                    %p.text-small.text-center メニューの詳細です。プレビュー・編集・グループの追加が行えます。
                    .box.has-middle-margin
                        .columns.is-mobile
                            .column.is-4
                                メニュー名：
                            .column.is-8
                                =@menu.menu_name
                                .is-float-right
                                    = link_to two_d_code_shop_menu_path(@menu, format: :pdf),target: :_blank, class:'button is-rounded is-small' do
                                        %i.fas.fa-qrcode
                                        Code
                                    = link_to edit_shop_menu_path(@menu),class:'button is-rounded is-small' do
                                        編集
                        .columns.is-mobile
                            .column.is-4
                                テーマカラー：
                            .column.is-8
                                .ball{style:"background-color:#{@menu.color};"}
                                = @menu.color
                        .columns.is-mobile
                            .column.is-4
                                プレビュー：
                            .column.is-8
                                = link_to user_menu_path(@menu),target: :_blank,class:"button is-rounded is-small" do
                                    %i.fas.fa-book-open
                                    メニューを開く
                            
                    -# アイテムグループリスト
                    -if @menu.item_groups.any?
                        .box.has-middle-margin
                            .text-center
                                %h3.text-large.has-under-line.is-inline-block
                                    アイテムグループ
                                %p.text-small メニュー内のグループです。
                            
                            .has-large-margin
                                .columns.is-mobile
                                    .column.is-3.text-small
                                        表示順
                                    .column.is-2
                                    .column.is-3.text-small
                                        グループ名
                                    .column.is-4
                                #grouplist
                                    =render 'grouplist',menu: @menu

                    -# アイテムグループ新規作成
                    .box.has-middle-margin
                        .text-center
                            %h3.text-large.has-under-line.is-inline-block
                                アイテムグループ新規作成
                            %p.text-small 新しいアイテムグループを作成します。
                        .has-large-margin
                            -if current_shop.categories.any?
                                = form_with model: ItemGroup.new, url: shop_menu_item_groups_path(@menu), local: true do |f|
                                    .field
                                        %span.label グループ画像
                                        .preview
                                        .control
                                            .field.has-addons
                                                %label.button.is-primary.is-small
                                                    %span
                                                        画像ファイルを選択
                                                        = f.attachment_field :group_image,style:"display:none"
                                                %input{type:"text",class:"input is-small is-primary",readonly:""}
                                    .field
                                        = f.label :category_id,'カテゴリー名',class:'label'
                                        .control
                                            .select.is-link.is-fullwidth
                                                = f.collection_select :category_id,current_shop.categories,:id,:name, {prompt:'グループ名を選択'}
                                    .field
                                        .control.text-center
                                            = f.submit 'グループ作成', class:'button is-link'
                            -else
                                .text-center
                                    %p 作成には先にカテゴリの登録が必要です。
                                    = link_to shop_categories_path, class:'button is-success' do
                                        %i.fas.fa-plus-circle
                                        カテゴリを登録
                            
            .text-center.text-small
                = link_to "戻る",shop_menus_path

app/views/shop/menus/two_d_code.html.haml
%p{style:"font-size:1.4em;"}
    = current_shop.shop_name
    さんの
    = @menu.menu_name
%div{style:"border-bottom:1px solid #{@menu.color}"}
%p
.codes
    -# 小サイズ 2*6=12個表示
    - 6.times do
        .color{style:"background-color:#{@menu.color};display:inline-block;"}
            .qrcode{style:"opacity:.8;"}
                = image_tag qrcode @url,290
        = image_tag qrcode @url,290
.codes
    -# 中サイズ 6個表示
    - 6.times do
        = image_tag qrcode @url,420

app/views/shop/menus/two_d_code.pdf.haml
%p{style:"font-size:1.4em;"}
    = current_shop.shop_name
    さんの
    = @menu.menu_name
    の2次元コード
%div{style:"border-bottom:1px solid #{@menu.color}"}
%p
.codes
    -# 2*6=12個表示
    - 6.times do
        .color{style:"background-color:#{@menu.color};display:inline-block;"}
            .qrcode{style:"opacity:.8;"}
                = image_tag qrcode @url,290
        = image_tag qrcode @url,290
.codes
    - 6.times do
        = image_tag qrcode @url,420