config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  devise_for :shops, skip: :all
  # devise 必要なルーティングのみ使用
  devise_scope :shop do
    get 'sign_up' => 'shops/registrations#new', as: :new_shop_registration
    post 'sign_up' => 'shops/registrations#create', as: :shop_registration
    post 'sing_up' => 'shops/passwords#new', as: :new_shop_password
    get 'sign_in' => 'shops/sessions#new', as: :new_shop_session
    post 'sign_in' => 'shops/sessions#create', as: :shop_session
    delete 'sign_out' => 'shops/sessions#destroy', as: :destroy_shop_session
  end

  # ユーザー
  namespace :user do
    # メニュー
    resources :menus, only:[:show] do
      resources :item_groups, only:[:show]
      resource :grin, only:[:create]
      resource :dizzy, only:[:create]
      resource :happy, only:[:create]
      # リクエスト
      resources :requests, only:[:create,:new] do
        get :thanks, on: :collection
      end
    end
  end

  # ショップ
  namespace :shop do
    # お問い合わせ
    resource :inquiry, only:[:new,:create] do
      post :confirm, on: :collection
    end
    resources :requests, only:[:index, :show, :destroy]
    resources :categories,except:[:show,:new]
    # マイページ
    resource :mypages,except:[:new,:create] do
      get :top, on: :collection
      get :cancel, on: :collection
      get :password, on: :collection
      get :howto, on: :collection
      patch :update_password, on: :collection
    end
    # エモーション
    resources :emotions, only:[:index] do
      get :reset, on: :collection
    end
    # メニュー(shallow true)
    resources :menus, except: :new, shallow: true do
      get :two_d_code, on: :member
      # アイテムグループ(shallow true)
      resources :item_groups,only:[:create,:destroy,:edit,:update], shallow: true do
        get :move_higher, on: :member
        get :move_lower, on: :member
        # メニューアイテム
        resources :menu_items, except: :new do
          get :move_higher, on: :member
          get :move_lower, on: :member
        end
      end
    end
  end

  # 管理者
  namespace :admin do
    resource :session, only:[:new, :create, :destroy]
    resources :shops, except:[:create,:new]
    resources :deleted_shops, only:[:index,:show]
    resource :tax, only:[:show,:edit,:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_admin-links.html.haml
%p.text-ex-small
    = link_to 'Shops',admin_shops_path
    ／
    = link_to 'DeletedShops',admin_deleted_shops_path
    ／
    = link_to 'Taxrate',admin_tax_path
    ／
    = link_to 'Logout',admin_session_path,method: :delete

app/views/admin/_sidebar.html.haml
.admin-sidebar
    .container
        .columns.is-mobile
            .column.is-10.is-offset-1.text-center
                %ul
                    %li.has-under-line.text-large
                        管理メニュー
                    %li.has-middle-margin
                        = link_to 'Shops',admin_shops_path,class:"button is-white is-block"
                    %li.has-middle-margin
                        = link_to 'DeletedShops',admin_deleted_shops_path,class:"button is-white is-block"
                    %li.has-middle-margin
                        = link_to 'Taxrate',admin_tax_path,class:"button is-white is-block"
                    %li.has-large-margin
                        = link_to 'Logout',admin_session_path,method: :delete,class:"button is-warning is-block"