config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  devise_for :shops, skip: :all
  # devise 必要なルーティングのみ使用
  devise_scope :shop do
    get 'sign_up' => 'shops/registrations#new', as: :new_shop_registration
    post 'sign_up' => 'shops/registrations#create', as: :shop_registration
    post 'sing_up' => 'shops/passwords#new', as: :new_shop_password
    get 'sign_in' => 'shops/sessions#new', as: :new_shop_session
    post 'sign_in' => 'shops/sessions#create', as: :shop_session
    delete 'sign_out' => 'shops/sessions#destroy', as: :destroy_shop_session
  end

  # ユーザー
  namespace :user do
    # メニュー
    resources :menus, only:[:show] do
      resources :item_groups, only:[:show]
      resource :grin, only:[:create]
      resource :dizzy, only:[:create]
      resource :happy, only:[:create]
      # リクエスト
      resources :requests, only:[:create,:new] do
        get :thanks, on: :collection
      end
    end
  end

  # ショップ
  namespace :shop do
    # お問い合わせ
    resource :inquiry, only:[:new,:create] do
      post :confirm, on: :collection
    end
    resources :requests, only:[:index, :show, :destroy]
    resources :categories,except:[:show,:new]
    # マイページ
    resource :mypages,except:[:new,:create] do
      get :top, on: :collection
      get :cancel, on: :collection
      get :password, on: :collection
      get :howto, on: :collection
      patch :update_password, on: :collection
    end
    # エモーション
    resources :emotions, only:[:index] do
      get :reset, on: :collection
    end
    # メニュー(shallow true)
    resources :menus, except: :new, shallow: true do
      get :two_d_code, on: :member
      # アイテムグループ(shallow true)
      resources :item_groups,only:[:create,:destroy,:edit,:update], shallow: true do
        get :move_higher, on: :member
        get :move_lower, on: :member
        # メニューアイテム
        resources :menu_items, except: :new do
          get :move_higher, on: :member
          get :move_lower, on: :member
        end
      end
    end
  end

  # 管理者
  namespace :admin do
    resource :session, only:[:new, :create, :destroy]
    resources :shops, except:[:create,:new]
    resources :deleted_shops, only:[:index,:show]
    resource :tax, only:[:show,:edit,:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deleted_shop.rb
class DeletedShop < ApplicationRecord
    
    # shopから複製するクラスメソッド
    def self.duplicate(shop)
        new(shop_name: shop.shop_name,
            postal_code: shop.postal_code,
            state: shop.state,
            city: shop.city,
            street: shop.street,
            phone_number: shop.phone_number,
            email: shop.email
        )
    end

    # shopから流用
    enum state: {
        北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
        茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
        新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
        岐阜県:21,静岡県:22,愛知県:23,三重県:24,
        滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
        鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
        徳島県:36,香川県:37,愛媛県:38,高知県:39,
        福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
    }
end

app/controllers/admin/deleted_shops_controller.rb
class Admin::DeletedShopsController < ApplicationController
    layout 'layouts/admin'
    before_action :current_admin
    before_action :require_admin_sign_in!

    def index
        @deleted_shops = DeletedShop.all.page(params[:page]).per(15)
    end
    
    def show
        @deleted_shop = DeletedShop.find(params[:id])
    end
end

app/views/admin/deleted_shops/index.html.haml
.columns.is-fullwidth
    .column.is-3-tablet.is-3-desktop.has-background-primary.is-hidden-mobile
        = render 'admin/sidebar'
    .column.is-9.has-background-white-ter
        .container
            = render 'admin/admin-links'
            .box
                %h1.text-large.has-under-line.has-text-danger 削除済み-Shop一覧
                %table.table.has-middle-margin.is-bordered.has-background-white-ter
                    %thead
                        %tr
                            %td
                                ID
                            %td
                                ショップ名
                            %td
                                削除日時
                            %td
                    %tbody
                        - @deleted_shops.each do |deleted_shop|
                            %tr
                                %td
                                    = deleted_shop.id
                                %td
                                    = deleted_shop.shop_name
                                %td
                                    = simple_date(deleted_shop.created_at)
                                %td
                                    .text-center
                                        = link_to "詳細",admin_deleted_shop_path(deleted_shop),class:"button is-small is-white"
            - if @deleted_shops.total_pages >= 2
                .paginate.has-small-margin
                    = paginate @deleted_shop

app/views/admin/deleted_shops/show.html.haml
.columns.is-fullwidth
    .column.is-3-tablet.is-3-desktop.has-background-primary.is-hidden-mobile
        = render 'admin/sidebar'
    .column.is-9.has-background-white-ter
        .container
            = render 'admin/admin-links'
            .box
                %h1.text-large.has-under-line.has-text-danger 削除済み-Shop詳細
                %table.table.has-middle-margin.is-bordered.has-background-white-ter
                    %tbody
                        %tr
                            %td
                                ショップ名
                            %td
                                = @deleted_shop.shop_name
                        %tr
                            %td
                                住所
                            %td
                                %p
                                    〒
                                    = postal_code(@deleted_shop.postal_code)
                                %p
                                    = @deleted_shop.state
                                    = @deleted_shop.city
                                    = @deleted_shop.street
                        %tr
                            %td
                                電話番号
                            %td
                                = @deleted_shop.phone_number
                        %tr
                            %td
                                email
                            %td
                                = @deleted_shop.email
            %p.text-center
                = link_to '削除済みショップ一覧',admin_deleted_shops_path