config/routes.rb
Rails.application.routes.draw do

  root 'pages#top'
  devise_for :shops, skip: :all
  # devise 必要なルーティングのみ使用
  devise_scope :shop do
    get 'sign_up' => 'shops/registrations#new', as: :new_shop_registration
    post 'sign_up' => 'shops/registrations#create', as: :shop_registration
    post 'sing_up' => 'shops/passwords#new', as: :new_shop_password
    get 'sign_in' => 'shops/sessions#new', as: :new_shop_session
    post 'sign_in' => 'shops/sessions#create', as: :shop_session
    delete 'sign_out' => 'shops/sessions#destroy', as: :destroy_shop_session
  end

  # ユーザー
  namespace :user do
    # メニュー
    resources :menus, only:[:show] do
      resources :item_groups, only:[:show]
      resource :grin, only:[:create]
      resource :dizzy, only:[:create]
      resource :happy, only:[:create]
      # リクエスト
      resources :requests, only:[:create,:new] do
        get :thanks, on: :collection
      end
    end
  end

  # ショップ
  namespace :shop do
    # お問い合わせ
    resource :inquiry, only:[:new,:create] do
      post :confirm, on: :collection
    end
    resources :requests, only:[:index, :show, :destroy]
    resources :categories,except:[:show,:new]
    # マイページ
    resource :mypages,except:[:new,:create] do
      get :top, on: :collection
      get :cancel, on: :collection
      get :password, on: :collection
      get :howto, on: :collection
      patch :update_password, on: :collection
    end
    # エモーション
    resources :emotions, only:[:index] do
      get :reset, on: :collection
    end
    # メニュー(shallow true)
    resources :menus, except: :new, shallow: true do
      get :two_d_code, on: :member
      # アイテムグループ(shallow true)
      resources :item_groups,only:[:create,:destroy,:edit,:update], shallow: true do
        get :move_higher, on: :member
        get :move_lower, on: :member
        # メニューアイテム
        resources :menu_items, except: :new do
          get :move_higher, on: :member
          get :move_lower, on: :member
        end
      end
    end
  end

  # 管理者
  namespace :admin do
    resource :session, only:[:new, :create, :destroy]
    resources :shops, except:[:create,:new]
    resources :deleted_shops, only:[:index,:show]
    resource :tax, only:[:show,:edit,:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user/dizzies_controller.rb
class User::DizziesController < ApplicationController
  before_action :set_menu
  before_action :reject_countinuous!

  def create
    shop = @menu.shop
    dizzy = Dizzy.new(shop_id: shop.id)
    dizzy.save
    session["shop#{@menu.shop_id}"] = "diz"
    respond_to do |format|
      format.js {@emotions = shop.emotions}
      format.html {redirect_to user_menu_path(@menu)}
    end
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  # 連投防止
  def reject_countinuous!
    redirect_to user_menu_path(@menu) if session["shop#{@menu.shop_id}"]
  end
end

app/controllers/user/grins_controller.rb
class User::GrinsController < ApplicationController
  before_action :set_menu
  before_action :reject_countinuous!

  def create
    shop = @menu.shop
    grin = Grin.new(shop_id: shop.id)
    grin.save
    session["shop#{@menu.shop_id}"] = "gri"
    respond_to do |format|
      format.js {@emotions = shop.emotions}
      format.html {redirect_to user_menu_path(@menu)}
    end
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  # 連投防止
  def reject_countinuous!
    redirect_to user_menu_path(@menu) if session["shop#{@menu.shop_id}"]
  end

end

app/controllers/user/happies_controller.rb
class User::HappiesController < ApplicationController
  before_action :set_menu
  before_action :reject_countinuous!

  def create
    shop = @menu.shop
    happy = Happy.new(shop_id: shop.id)
    happy.save
    session["shop#{@menu.shop_id}"] = "hap"
    respond_to do |format|
      format.js {@emotions = shop.emotions}
      format.html {redirect_to user_menu_path(@menu)}
    end
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  # 連投防止
  def reject_countinuous!
    redirect_to user_menu_path(@menu) if session["#{@menu.shop_id}"]
  end
end

app/controllers/user/item_groups_controller.rb
class User::ItemGroupsController < ApplicationController
    layout 'layouts/user'
    
    def show
        @menu = Menu.find(params[:menu_id])
        @item_group = ItemGroup.find(params[:id])
        @emotions = @menu.shop.emotions
    end
end

app/controllers/user/menus_controller.rb
class User::MenusController < ApplicationController
    layout 'layouts/user'
    
    def show
        @menu = Menu.find(params[:id])
        @emotions = @menu.shop.emotions
    end
end

app/controllers/user/requests_controller.rb
class User::RequestsController < ApplicationController
    layout 'user'

    def new
        @menu = Menu.find(params[:menu_id])
    end

    def create
        @menu = Menu.find(params[:menu_id])
        @request = Request.new(request_params)
        @request.shop_id = @menu.shop_id
        if @request.save
            redirect_to thanks_user_menu_requests_path(@menu)
        else
            render :new
        end
    end

    def thanks
        @menu = Menu.find(params[:menu_id])
    end

    private
    def request_params
        params.require(:request).permit(:title,:message)
    end
end

app/views/user/_emotions.html.haml
.emotions
    %table.block-center
        %tr.text-ex-large
            -unless session["shop#{@menu.shop_id}"]
                %td
                    = link_to user_menu_grin_path(@menu),method: :post, remote: true,data:{disable_with:''} do
                        %i.far.fa-grin
                %td
                    = link_to user_menu_happy_path(@menu),method: :post, remote: true do
                        %i.far.fa-grin-squint
                %td
                    = link_to user_menu_dizzy_path(@menu),method: :post, remote: true, data:{disable_with:''} do
                        %i.far.fa-dizzy
            -else
                %td{class:("has-text-danger" if session["shop#{@menu.shop_id}"] == "gri")}
                    %i.far.fa-grin
                %td{class:("has-text-danger" if session["shop#{@menu.shop_id}"] == "hap")}
                    %i.far.fa-grin-squint
                %td{class:("has-text-danger" if session["shop#{@menu.shop_id}"] == "diz")}
                    %i.far.fa-dizzy
        %tr.text-ex-small
            %td
                .text-center
                    = emotions[:grin]
            %td
                .text-center
                    = emotions[:happy]
            %td
                .text-center
                    = emotions[:dizzy]

app/views/user/_header.html.haml
%header#user-header{style:"background-color:#{menu.color}"}
    .columns.is-mobile
        .column.text-center
            %span.button.is-small.is-rounded.header-btn#menu-btn3
                %i.fa.fa-bars

#menu-overlay
    .columns.is-gapless#user-menu-modal
        .column.is-3
        .column.is-6.user-menu-list.text-center{style:"background-color:#{menu.color}"}
            %ul
                = link_to user_menu_path(@menu) do
                    %li
                        .grey-shadow
                            %i.fas.fa-home
                            = @menu.menu_name
                = link_to new_user_menu_request_path(@menu) do
                    %li
                        .grey-shadow
                            %i.fas.fa-envelope
                            ご意見・ご要望